export const environment = {
  production: true,
  createUser: "/api/user/create",
  allUsers: "/api/user/allUsers",
  updateUser: "/api/user/update",
  removeUser: "/api/user/remove",
  createRequirement: "/api/requirement/create",
  allRequirements: "/api/requirement/allRequirements",
  updateRequirement: "/api/requirement/update",
  removeRequirement: "/api/requirement/remove",
  createCourse: "/api/course/create",
  allCourses: "/api/course/allCourses",
  updateCourse: "/api/course/update",
  removeCourse: "/api/course/remove",
};
